# Generated by Django 5.2 on 2025-04-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cityObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='markers/')),
                ('rating', models.IntegerField()),
                ('category', models.CharField(choices=[('toilet', 'Санузел'), ('water', 'Пополнение воды'), ('rest', 'Зона отдыха')], max_length=20)),
                ('moderated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'map_cityobject',
            },
        ),
    ]
