# Generated by Django 4.2.21 on 2025-06-04 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0002_cityobject_moderation_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cityobject',
            options={'permissions': [('can_moderate_cityobjects', 'Can moderate city objects')]},
        ),
        migrations.AddField(
            model_name='cityobject',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='cityobject',
            table=None,
        ),
    ]
